// source: pdfgen.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.pdfgen.GenerateRequest', null, global);
goog.exportSymbol('proto.pdfgen.GenerateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pdfgen.GenerateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pdfgen.GenerateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pdfgen.GenerateRequest.displayName = 'proto.pdfgen.GenerateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pdfgen.GenerateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pdfgen.GenerateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pdfgen.GenerateResponse.displayName = 'proto.pdfgen.GenerateResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pdfgen.GenerateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pdfgen.GenerateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pdfgen.GenerateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pdfgen.GenerateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dpi: jspb.Message.getFieldWithDefault(msg, 2, 0),
    zoom: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    pagesize: jspb.Message.getFieldWithDefault(msg, 4, ""),
    orientation: jspb.Message.getFieldWithDefault(msg, 5, ""),
    grayscale: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    marginleft: jspb.Message.getFieldWithDefault(msg, 7, ""),
    marginright: jspb.Message.getFieldWithDefault(msg, 8, ""),
    margintop: jspb.Message.getFieldWithDefault(msg, 9, ""),
    marginbottom: jspb.Message.getFieldWithDefault(msg, 10, ""),
    htmlbody: jspb.Message.getFieldWithDefault(msg, 11, ""),
    htmlheader: jspb.Message.getFieldWithDefault(msg, 12, ""),
    htmlfooter: jspb.Message.getFieldWithDefault(msg, 13, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pdfgen.GenerateRequest}
 */
proto.pdfgen.GenerateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pdfgen.GenerateRequest;
  return proto.pdfgen.GenerateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pdfgen.GenerateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pdfgen.GenerateRequest}
 */
proto.pdfgen.GenerateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDpi(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setZoom(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPagesize(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrientation(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGrayscale(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarginleft(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarginright(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setMargintop(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarginbottom(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setHtmlbody(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setHtmlheader(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setHtmlfooter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pdfgen.GenerateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pdfgen.GenerateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pdfgen.GenerateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pdfgen.GenerateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDpi();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getZoom();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getPagesize();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getOrientation();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getGrayscale();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getMarginleft();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getMarginright();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getMargintop();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getMarginbottom();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getHtmlbody();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getHtmlheader();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getHtmlfooter();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 dpi = 2;
 * @return {number}
 */
proto.pdfgen.GenerateRequest.prototype.getDpi = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setDpi = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional double zoom = 3;
 * @return {number}
 */
proto.pdfgen.GenerateRequest.prototype.getZoom = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setZoom = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string pageSize = 4;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getPagesize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setPagesize = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string orientation = 5;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getOrientation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setOrientation = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool grayscale = 6;
 * @return {boolean}
 */
proto.pdfgen.GenerateRequest.prototype.getGrayscale = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setGrayscale = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string marginLeft = 7;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getMarginleft = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setMarginleft = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string marginRight = 8;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getMarginright = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setMarginright = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string marginTop = 9;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getMargintop = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setMargintop = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string marginBottom = 10;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getMarginbottom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setMarginbottom = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string htmlBody = 11;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getHtmlbody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setHtmlbody = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string htmlHeader = 12;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getHtmlheader = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setHtmlheader = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string htmlFooter = 13;
 * @return {string}
 */
proto.pdfgen.GenerateRequest.prototype.getHtmlfooter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateRequest} returns this
 */
proto.pdfgen.GenerateRequest.prototype.setHtmlfooter = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pdfgen.GenerateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pdfgen.GenerateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pdfgen.GenerateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pdfgen.GenerateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    pdf: msg.getPdf_asB64(),
    error: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pdfgen.GenerateResponse}
 */
proto.pdfgen.GenerateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pdfgen.GenerateResponse;
  return proto.pdfgen.GenerateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pdfgen.GenerateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pdfgen.GenerateResponse}
 */
proto.pdfgen.GenerateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPdf(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pdfgen.GenerateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pdfgen.GenerateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pdfgen.GenerateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pdfgen.GenerateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPdf_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bytes pdf = 1;
 * @return {!(string|Uint8Array)}
 */
proto.pdfgen.GenerateResponse.prototype.getPdf = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes pdf = 1;
 * This is a type-conversion wrapper around `getPdf()`
 * @return {string}
 */
proto.pdfgen.GenerateResponse.prototype.getPdf_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPdf()));
};


/**
 * optional bytes pdf = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPdf()`
 * @return {!Uint8Array}
 */
proto.pdfgen.GenerateResponse.prototype.getPdf_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPdf()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.pdfgen.GenerateResponse} returns this
 */
proto.pdfgen.GenerateResponse.prototype.setPdf = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string error = 2;
 * @return {string}
 */
proto.pdfgen.GenerateResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pdfgen.GenerateResponse} returns this
 */
proto.pdfgen.GenerateResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.pdfgen);
